{{- range $services := .Values.services -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $services.name }}
  labels:
    app: {{ $services.label }}
spec:
  ports:
  - port: {{ $services.port }}
    name: {{ $services.name }}
  clusterIP: None
  selector:
    app: {{ $services.label }}
---
{{- end -}}